### PR TITLE
Add support for Pekko 1.0.2

### PR DESCRIPTION
**Pull request by JD557**
Adds `pekko-bundle`, `pekko-classic` and `pekko-typed` subprojects, so that this library can be used with Pekko 1.0.2.

One thing to note is that the packages are still under `net.ruippeixotog.akka`. The reasoning for this is to be able to use a common `core`, as some objects are marked as `private[specs2]`.

If it's desirable to have the new code under `net.ruippeixotog.pekko`, here's some possible solutions:
- Copy the `core` as well to `pekko-core`
- Change the private visibility to `private[net.ruippeixotog]` (or to public)

### CODE REVIEW

**Review by ruippeixotog — CHANGES_REQUESTED** [review]
Hey @JD557, thanks for the PR! I'm a bit concerned that this led to a lot of duplicated code to support what is essentially the same interface, though. Do you think it would be challenging to create a `core` project containing the library-independent logic for matching (maybe using a type class exposing relevant operations from `TestKitBase`?) and having 4 implementations for each actor library?

I don't have strong feelings on package naming, but I'm fine with changing method visibility to allow for better packaging. I'd probably also rename akka SBT projects to have "akka" explicitly now that not every project uses akka.

**Comment by JD557** [comment]
> Do you think it would be challenging to create a core project containing the library-independent logic for matching (maybe using a type class exposing relevant operations from TestKitBase?) and having 4 implementations for each actor library?

Moved things to common traits in `22ab149`, `49efba6` and `1c8932a` (`net.ruippeixotog.akka.testkit.specs2.impl.ClassicMatchers` and `net.ruippeixotog.akka.testkit.specs2.impl.TypedMatchers` in the `core` project).

> I don't have strong feelings on package naming, but I'm fine with changing method visibility to allow for better packaging.

Turns out that with the change above I didn't have to change the `Matchers` visibility. I did mark those new objects as `private[ruippeixotog]`, though.

I ended up renaming the pekko packages to `net.ruippeixotog.pekko`. From experience, it's actually quite convenient to run something like `rg "Akka|akka"` to see if everything is migrated to pekko, and having those `net.ruippeixotog.akka` packages is a bit annoying 😅 .

> I'd probably also rename akka SBT projects to have "akka" explicitly now that not every project uses akka.

Done in `c615966)`

**Review by ruippeixotog — CHANGES_REQUESTED** [review]
Sorry for the huge delay reviewing this :(

This all looks good to me. I only have one last ask: instead of having a flat list of project folders, can we organize them a bit? Ideally we'd have something like:

```
core/
    build.sbt
akka/
    build.sbt
    classic/
        build.sbt
    typed/
        build.sbt
pekko/
    build.sbt
    classic/
        build.sbt
    typed/
        build.sbt
```

The only thing I don't know if you'll be able to have `akka` and `akka/classic` as roots of different SBT projects, but if it doesn't work I don't mind us using `akka/bundle` instead.

Once you change this I'll merge this and release a new version.

**Comment by JD557** [comment]
Sorry for the very long delay, I completely forgot about this PR 🙃 

Changed the directory structure in [806628c](https://github.com/ruippeixotog/akka-testkit-specs2/pull/198/commits/806628cdc1c997bf618cd5c6c90c0546a90a5896).

From what I can tell from a quick test and publish local, it seems to be working.

**Review by ruippeixotog — APPROVED** [review]
Thanks @JD557, looks good!

**Pull request merged**
